layout_spectrum: 0.4412588
typography_spectrum: 0.9864668
color:
  saturation: 0.5701005
  lightness: 0.3429378
  brandStrength: 1
  brandColors:
    - '#06030B'
    - '#391E0F'
    - '#654120'
    - '#A3642F'
    - '#FEFEFE'
  rhythmicContrast: 0.7275959
name: loretto
